### ISSUE TITLE
Style folder mövcud deyil.

### ISSUE THREAD

**Issue by nasirmovlamov** [Arif5H/Lesson1_frontend#1]
Dərsdə demişdim ki, style.css filenızı style folderi yaradıb onun içərisinə qoyub sonra link verin

**Comment by Arif5H** [comment]
Duzeltmisdimde issue dan sonra saat 17:00

**Comment by nasirmovlamov** [comment]
Bəs burda commentlə qeyd edin mənə notification gəlsində, bunun barədə:) 👍
